theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme Colors (UVU Brand Colors)
colors:
  primary: "#275D38"    # UVU Green
  secondary: "#FFDB05"  # UVU Yellow
  dark: "#1A4027"      # Dark Green
  light: "#F5F5F5"     # Light Gray
  text: "#333333"      # Dark Gray

# Site Information
title: UVU Computer Science Department
tagline: Shaping Tomorrow's Tech Leaders
description: >-
  Utah Valley University's Computer Science Department offers cutting-edge programs 
  in software engineering, artificial intelligence, and data science. Join us to 
  shape the future of technology.
url: "https://memari-majid.github.io"
baseurl: "/UVU-CS-Program_Analyzer"
logo: UVU_logo.png
show_downloads: false

# Department Information
department:
  name: Computer Science Department
  address: 800 W University Parkway
  city: Orem
  state: UT
  zip: 84058
  building: Computer Science Building
  room: CS-520
  phone: (801) 863-8218
  email: cs@uvu.edu
  hours: Monday-Friday 8:00 AM - 5:00 PM

# Program Information
programs:
  computer_science:
    name: Computer Science (BS)
    description: Our flagship program preparing students for diverse careers in software development
    career_paths:
      - Software Engineer
      - Systems Architect
      - Full-Stack Developer
    starting_salary: "$65,000 - $95,000"
    job_growth: "26% through 2032"
  
  data_science:
    name: AI & Data Science (BS)
    description: Cutting-edge program combining computer science with data analytics
    career_paths:
      - Data Scientist
      - Machine Learning Engineer
      - AI Developer
    starting_salary: "$75,000 - $110,000"
    job_growth: "41% annual growth"
  
  software_engineering:
    name: Software Engineering (BS)
    description: Specialized program focusing on large-scale software systems
    career_paths:
      - Software Architect
      - Project Manager
      - Technical Lead
    starting_salary: "$70,000 - $100,000"
    job_growth: "33% growth rate"

# Navigation
nav_pages:
  - title: Programs
    url: https://www.uvu.edu/cs/degrees/
    icon: bi-book
  - title: Faculty
    url: https://www.uvu.edu/cs/
    icon: bi-people
  - title: Research
    url: https://www.uvu.edu/cs/
    icon: bi-graph-up
  - title: Resources
    url: https://www.uvu.edu/cs/
    icon: bi-tools
  - title: Contact
    url: https://www.uvu.edu/cs/
    icon: bi-envelope

# Social Media
social_links:
  facebook: uvucs
  linkedin: school/uvucs
  instagram: uvucs

# Quick Links
quick_links:
  - title: Department Website
    url: https://www.uvu.edu/cs/
  - title: Programs & Degrees
    url: https://www.uvu.edu/cs/degrees/
  - title: NSF Scholarship
    url: https://www.uvu.edu/cet/nsfscholarship/
  - title: Internships
    url: https://www.uvu.edu/cet/internships/computer-science/
  - title: Apply Now
    url: https://www.uvu.edu/admissions/

# SEO Settings
author: UVU Computer Science Department
keywords: >-
  computer science, programming, technology, education, utah valley university, 
  UVU, CS, software engineering, artificial intelligence, data science, 
  machine learning, web development, cybersecurity, silicon slopes
google_analytics: # your Google Analytics tracking ID

# Build settings
markdown: kramdown
sass:
  style: compressed 