remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: UVU Computer Science Programs
description: Shape your future in technology at Utah Valley University
logo: https://www.uvu.edu/brand/images/logos/uvu-logo.png
show_downloads: false

# Site Settings
url: "" # the base hostname & protocol, e.g., http://example.com
baseurl: "" # the subpath of your site, e.g., /blog

# Social Links (shown in footer)
social_links:
  github: UVU-CS
  linkedin: uvu
  twitter: uvucs

# SEO Settings
author: UVU Computer Science Department
keywords: computer science, programming, technology, education, utah valley university
google_analytics: # your Google Analytics tracking ID

# Theme colors
colors:
  header: "#275D38"  # UVU Green
  link: "#275D38"    # UVU Green
  section: "#1A4027" # Dark Green
  
# Navigation
header_pages:
  - Programs
  - Future
  - Silicon Slopes
  - Contact 